services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "studiesdb"
    ports:
      - "3306:3306"
    volumes:
      - /studiesgroup/mysql:/var/lib/mysql
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
networks:
  db:
    driver: bridge